<?php

declare(strict_types=1);

use Infrangible\BackendWidget\Block\Form\Back;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Back $block */
?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('#<?= $block->getButtonId(); ?>').on('click', function () {
            var editForm = $('#<?= $block->getFormId(); ?>');
            var editFormParent = editForm.parent().parent();
            editForm.notification();
            editForm.notification('clear');
            $.ajax({
                url: '<?= $block->getButtonUrl(); ?>',
                method: 'get',
                dataType: 'html',
                showLoader: true,
                context: editFormParent[0],
                success: function (data) {
                    var targetNode = editFormParent;
                    targetNode.html(data);
                    targetNode.trigger('contentUpdated');
                }
            });
        });
    });
</script>
