<?php

declare(strict_types=1);

use Infrangible\BackendWidget\Block\Grid\Tab\Add;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */
?>

<?php /** @var Php $this */ ?>
<?php /** @var Add $block */ ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('#<?= $block->getButtonId(); ?>').on('click', function () {
            var grid = $('#<?= $block->getGridId(); ?>').parent();
            $.ajax({
                url: '<?= $block->getButtonUrl(); ?>',
                method: 'get',
                dataType: 'html',
                showLoader: true,
                context: grid[0],
                success: function (data) {
                    var targetNode = grid;
                    targetNode.html(data);
                    targetNode.trigger('contentUpdated');
                }
            });
        });
    });
</script>
